YapayZekaFinal-main/WebApplication1/WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Models/Footballer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Footballer
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Takim { get; set; }
        public String Pozisyon { get; set; }
        public int Yas { get; set; }
    }
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Models/FootballerData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class FootballerData
    {

        public static List<Footballer> Footballers = new List<Footballer>()
        {

            new Footballer()
            {
                Id = 31,
                Ad = "Ederson Moraes",
                Takim = "Manchester City",
                Pozisyon = "Goalkeeper",
                Yas = 28
            },
            new Footballer()
            {
                Id = 66,
                Ad = "Trent Alexander-Arnold",
                Takim = "Liverpool",
                Pozisyon = "Defender",
                Yas = 23
            },
            new Footballer()
            {
                Id = 3,
                Ad = "Ruben Dias",
                Takim = "Manchester City",
                Pozisyon = "Defender",
                Yas = 24
            },
            new Footballer()
            {
                Id = 4,
                Ad = "Virgil van Dijk",
                Takim = "Liverpool",
                Pozisyon = "Defender",
                Yas = 30
            },
            new Footballer()
            {
                Id = 20,
                Ad = "Joao Cancelo",
                Takim = "Manchester City",
                Pozisyon = "Defender",
                Yas = 27
            },
            new Footballer()
            {
                Id = 20,
                Ad = "Bernardo Silva",
                Takim = "Manchester City",
                Pozisyon = "Midfielder",
                Yas = 27
            },
            new Footballer()
            {
                Id = 23,
                Ad = "Conor Gallagher",
                Takim = "Crystal Palace",
                Pozisyon = "Midfielder",
                Yas = 21
            },
            new Footballer()
            {
                Id = 17,
                Ad = "Kevin De Bruyne",
                Takim = "Manchester City",
                Pozisyon = "Midfielder",
                Yas = 30
            },
            new Footballer()
            {
                Id = 7,
                Ad = "Cristiano Ronaldo",
                Takim = "Manchester United",
                Pozisyon = "Forward",
                Yas = 36
            },
            new Footballer()
            {
                Id = 20,
                Ad = "Diogo Jota",
                Takim = "Liverpool",
                Pozisyon = "Forward",
                Yas = 25
            },
            new Footballer()
            {
                Id = 11,
                Ad = "Mohamed Salah Ghaly",
                Takim = "Liverpool",
                Pozisyon = "Forward",
                Yas = 29
            }
        };
    }
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Controllers/FootballerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class FootballerController : Controller
    {

        public IActionResult Listele()
        {
            return View(Models.FootballerData.Footballers);
            
        }

        public IActionResult Ekle()
        {
            return View();
        }

        
        [HttpPost]
        public IActionResult Ekle(Models.Footballer newFootballer)
        {
            Models.FootballerData.Footballers.Add(newFootballer);
            return RedirectToAction("Listele"); 
        }


        public IActionResult Guncelle(int id)
        {
            var guncelle = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == id);
            return View(guncelle);
        }

        [HttpPost]
        public IActionResult Guncelle(Models.Footballer footballer)
        {

            var guncelleOrj = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == footballer.Id);

            var guncelle = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == footballer.Id);

            guncelle.Ad = footballer.Ad;
            guncelle.Takim = footballer.Takim;
            guncelle.Pozisyon = footballer.Pozisyon;
            guncelle.Yas = footballer.Yas;


            Models.FootballerData.Footballers.Remove(guncelleOrj);
            Models.FootballerData.Footballers.Add(guncelle); 

            return RedirectToAction("Listele");
           
        }



        public IActionResult Detaylar(int id)//Parametre degeri girdim
        {
            var detay = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == id);
            return View(detay); 

        }


        public IActionResult Sil(int id)
        {
            var sil = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == id);
            return View(sil); 
        }


        [HttpPost]
        public IActionResult Sil(Models.Footballer footballer)
        {
            var sil = Models.FootballerData.Footballers.FirstOrDefault(b => b.Id == footballer.Id);
            Models.FootballerData.Footballers.Remove(sil);
            return RedirectToAction("Listele"); 
        }


    }
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Footballer/Detaylar.cshtml
@model WebApplication1.Models.Footballer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Takim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Takim)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pozisyon)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pozisyon)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Yas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Yas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Guncelle", new {  id = Model.Id }) |
    <a asp-action="Listele">Back to List</a>
</div>

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Footballer/Ekle.cshtml
@model WebApplication1.Models.Footballer

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Ekle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Takim" class="control-label"></label>
                <input asp-for="Takim" class="form-control" />
                <span asp-validation-for="Takim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pozisyon" class="control-label"></label>
                <input asp-for="Pozisyon" class="form-control" />
                <span asp-validation-for="Pozisyon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yas" class="control-label"></label>
                <input asp-for="Yas" class="form-control" />
                <span asp-validation-for="Yas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Listele">Back to List</a>
</div>

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Footballer/Guncelle.cshtml
@model WebApplication1.Models.Footballer

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Guncelle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Takim" class="control-label"></label>
                <input asp-for="Takim" class="form-control" />
                <span asp-validation-for="Takim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pozisyon" class="control-label"></label>
                <input asp-for="Pozisyon" class="form-control" />
                <span asp-validation-for="Pozisyon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Yas" class="control-label"></label>
                <input asp-for="Yas" class="form-control" />
                <span asp-validation-for="Yas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Listele">Back to List</a>
</div>

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Footballer/Listele.cshtml
@model IEnumerable<WebApplication1.Models.Footballer>

@{
    ViewData["Title"] = "Footballers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3 class="text-center">Best Of the First Half</h3> <br>
<table class="table">
    <thead class="bg-dark text-white">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Takim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pozisyon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Yas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Takim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pozisyon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yas)
            </td>
            <td>
                <button type="button" class="btn alert-secondary" style="width:64px; padding:1px"> @Html.ActionLink("Edit", "Guncelle", new { id = item.Id }, new { style = "color: Black;" })</button>
                <button type="button" class="btn alert-secondary" style="width:62px; padding:1px"> @Html.ActionLink("Details", "Detaylar", new { id = item.Id }, new { style = "color: Black;" })</button>
                <button type="button" class="btn alert-secondary" style="width:60px; padding:1px"> @Html.ActionLink("Delete", "Sil", new { id = item.Id }, new { style = "color: Black;" })</button>
            </td>
        </tr>
}
    </tbody>
</table>

<p>
  <button type="button" class="btn btn-light" style="width:100%; padding:1px">  <a asp-action="Ekle"> Add New Player </a></button>
</p>

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Footballer/Sil.cshtml
@model WebApplication1.Models.Footballer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<div>
  
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Takim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Takim)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pozisyon)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pozisyon)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Yas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Yas)
        </dd>
    </dl>
    
    <form asp-action="Sil">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Listele">Back to List</a>
    </form>
</div>

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="container">
 <div class="container-fluid font-italic p-5  text-dark text-center">
  <h1>Premier League</h1>
  <p>"Welcome to the best League in the World"</p> 
</div>

<div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
       <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
       <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class=" w-100" src="~/foto/slide1.jpg" alt="First slide" height="600px">
    </div>
    <div class="carousel-item">
      <img class=" w-100" src="~/foto/slide2.jpg" alt="Second slide" height="600px">
    </div>
    <div class="carousel-item">
      <img class=" w-100" src="~/foto/slide3.jpg" alt="Third slide" height="600px">
    </div>
      <div class="carousel-item">
      <img class=" w-100" src="~/foto/slide4.jpg" alt="Third slide" height="600px">
    </div>
     <div class="carousel-item">
      <img class=" w-100" src="~/foto/slide5.jpg" alt="Third slide" height="600px">
    </div>
        <div class="carousel-item">
      <img class=" w-100" src="~/foto/slide6.jpg" alt="Third slide" height="600px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
	 <div class="row bolum1 mt-5 align-items-center">
	 
	 
	 </div>
	  
	 <div class="container">
	  <div class="row bolum2">
	 <div class="col">
		 <h1 class="display-2 text-center">Teams</h1> <br>
		 
	</div>
	
	 
	 </div>
		 <div class="row-15 text-center"> 
		
  
    <img src="~/foto/liverpool.png" alt="" width="50" height="50" >
     <img src="~/foto/manu.png" alt="" width="50" height="50">
      <img src="~/foto/chelsea.png" alt="" width="50" height="50">
       <img src="~/foto/everton.png" alt="" width="50" height="50">
        <img src="~/foto/Arsenal.png" alt="" width="50" height="50">
         <img src="~/foto/Aston_Villa.png" alt="" width="50" height="50">
          <img src="~/foto/manc.png" alt="" width="50" height="50">
           <img src="~/foto/leeds.png" alt="" width="50" height="50">
            <img src="~/foto/Brentford.png" alt="" width="50" height="50">
             <img src="~/foto/BrightonHove.png" alt="" width="50" height="50">
              <img src="~/foto/Burnley_logo.png" alt="" width="50" height="50">
           <img src="~/foto/Crystal.png" alt="" width="50" height="50">
           <img src="~/foto/Newcastle.png" alt="" width="50" height="50">
           <img src="~/foto/Norwich.png" alt="" width="50" height="50">
           <img src="~/foto/Leicester.png" alt="" width="50" height="50">
           <img src="~/foto/watford.png" alt="" width="50" height="50">
           <img src="~/foto/Westham.png" alt="" width="50" height="50">
           
           <img src="~/foto/spurs.png" alt="" width="50" height="50">
           <img src="~/foto/Southampton.png" alt="" width="50" height="50">

		 
		 
		 
		 
		 </div>
	 </div>
     <br>
      <br>
       <br>
        <br>


            <div class="row">
                <div class="col-lg12 col-md-12 col-sm-12">
                    <h2>Contact</h2>
                    <form>
                        <div class="form-group">
                          <label for="ad">Name:</label>
                          <input type="text" class="form-control" id="ad">
                          <label for="soyad">Surname:</label>
                          <input type="password" class="form-control" id="soyad">
                          <label for="mail">E-mail:</label>
                          <input type="text" class="form-control" id="mail">
                          <label for="yorum">Message:</label>
                          <textarea class="form-control" rows="5" id="yorum"></textarea>
                          <br />
                          <button type="button" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
            
            

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Odev/Predict.cshtml
@model WebApplication1.MLModel.ModelInput
@{
    ViewData["Title"] = "Prediction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Home Team Corner Prediction</h1>




@if(ViewBag.Result != null)
{
      <div>
          <h4 class="text-center">
              Result : @ViewBag.Result.Score
          </h4>
      </div>

  <hr>
}<br>

 <div class="row">
    <div class="col-md-12">
        <img class="w-50 float-right" src="~/foto/logo.png" alt="">
        <form asp-action="Predict">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          

                <div class="form-group col-md-4">
                       <div class="form-group row">
                           <label asp-for="HomeTeam" class="control-label">Home Team</label>
                    <input asp-for="HomeTeam" class="form-control" />
                    <span asp-validation-for="HomeTeam" class="text-danger"></span>
                </div>
               
                     <div class="form-group row">
                         <label asp-for="AwayTeam" class="control-label">Away Team</label>
                    <input asp-for="AwayTeam" class="form-control" />
                    <span asp-validation-for="AwayTeam" class="text-danger"></span>
                </div>
             
                 <div class="form-group row">
               
                
                     <label asp-for="HomeShot" class="control-label">Home Shot</label>
                    <input asp-for="HomeShot" class="form-control" />
                    <span asp-validation-for="HomeShot" class="text-danger"></span>
                </div>
               
                 <div class="form-group row">
                 
                     <label asp-for="AwayShot" class="control-label">AwayShot</label>
                    <input asp-for="AwayShot" class="form-control" />
                    <span asp-validation-for="AwayShot" class="text-danger"></span>
                </div>
               
                 <div class="form-group row">
              
                     <label asp-for="AwayCorner" class="control-label">Away Corner</label>
                    <input asp-for="AwayCorner" class="form-control" />
                    <span asp-validation-for="AwayCorner" class="text-danger"></span>
                </div>
                
               <br>
                <div class="form-group text-right">
                    <input type="submit" value="Prediction" class="btn btn-dark" />
                
                </div>
            </div>
        </form>
        
    </div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

YapayZekaFinal-main/WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="~/foto/sekme.png" >
    <title>@ViewData["Title"] - Premier League</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img class="w-25 float-left" src="~/foto/logo.png" alt=""> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">News</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Footballer" asp-action="Listele">Footballers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Odev" asp-action="Predict">Prediction</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Premier League - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>